/* Fishing Tales — ocean chapter. All scores, encounter sizes and tackle effects are fictional. */
(() => {
'use strict';
const D=window.FishingData,$=id=>document.getElementById(id),KEY='fishing_tales_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),rand=(a,b)=>a+Math.random()*(b-a),find=id=>D.fish.find(f=>f.id===id);
const fresh=()=>({version:1,records:{},works:[],best:{casual:0,challenge:0},legacy:[]});
let save=fresh(),storageOK=true;
try { const raw=localStorage.getItem(KEY);if(raw)save=validateSave(JSON.parse(raw));else{const old=JSON.parse(localStorage.getItem('fishing_ocean_collection')||'[]');if(Array.isArray(old)){save.legacy=old.filter(x=>typeof x==='string');for(const id of save.legacy)if(find(id))save.records[id]={count:0,max:0,first:null,legacy:true};}} }catch{storageOK=false;}
function validColor(s){return typeof s==='string'&&/^#[\da-f]{6}$/i.test(s);}
function cleanCapture(c){return c&&Number.isFinite(c.size)&&typeof c.date==='string'?{size:clamp(c.size,0,10000),date:c.date.slice(0,40),mode:c.mode==='challenge'?'challenge':'casual',rod:String(c.rod||'').slice(0,20),bait:String(c.bait||'').slice(0,20)}:null;}
function validateSave(s){
  if(!s||s.version!==1||!s.records||!Array.isArray(s.works)||s.works.length>500)throw Error('不支援的備份格式');
  const clean=fresh();
  for(const f of D.fish){const r=s.records[f.id];if(!r)continue;if(!Number.isFinite(r.count)||r.count<0||r.count>1e8||!Number.isFinite(r.max)||r.max<0||r.max>10000)throw Error('捕獲紀錄格式錯誤');clean.records[f.id]={count:Math.floor(r.count),max:r.max,first:typeof r.first==='string'?r.first.slice(0,40):null,legacy:!!r.legacy,largest:cleanCapture(r.largest)};}
  const ids=new Set();
  clean.works=s.works.map(w=>{if(!w||!find(w.fishId)||typeof w.id!=='string'||ids.has(w.id)||!Array.isArray(w.strokes)||w.strokes.length>160||!validColor(w.base)||!['ivory','sand','mist'].includes(w.paper))throw Error('作品格式錯誤');ids.add(w.id);const strokes=w.strokes.map(t=>{if(!validColor(t.color)||!Number.isFinite(t.size)||t.size<1||t.size>150||!Number.isFinite(t.opacity)||t.opacity<0||t.opacity>1||!Array.isArray(t.points)||t.points.length>2500||t.points.some(p=>!Array.isArray(p)||p.length!==2||p.some(v=>!Number.isFinite(v)||v<0||v>1000)))throw Error('筆觸格式錯誤');return {color:t.color,size:t.size,opacity:t.opacity,points:t.points};});return {id:w.id,fishId:w.fishId,title:String(w.title||'海的記憶').slice(0,36),signature:String(w.signature||'').slice(0,18),date:String(w.date||'').slice(0,40),capture:w.capture&&Number.isFinite(w.capture.size)?{size:clamp(w.capture.size,0,10000),date:String(w.capture.date||'').slice(0,40),mode:w.capture.mode==='challenge'?'challenge':'casual',rod:String(w.capture.rod||'').slice(0,20),bait:String(w.capture.bait||'').slice(0,20)}:null,paper:w.paper,base:w.base,seal:!!w.seal,pinned:!!w.pinned,strokes};});
  for(const mode of ['casual','challenge'])clean.best[mode]=Number.isFinite(s.best?.[mode])?clamp(Math.floor(s.best[mode]),0,1e9):0;
  clean.legacy=Array.isArray(s.legacy)?s.legacy.filter(x=>typeof x==='string').slice(0,100):[];return clean;
}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));storageOK=true;return true;}catch{storageOK=false;toast('儲存空間不足或被封鎖。請先匯出備份；目前進度只留在這次開啟。');return false;}}
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500);}
const atlas=new Image(),ocean=new Image();let artReady=false,assetFailed=false;
const loadImage=(image,src)=>new Promise(resolve=>{image.onload=()=>resolve(true);image.onerror=()=>resolve(false);image.src=src;});
Promise.all([loadImage(atlas,'assets/fishing/marine-atlas.webp'),loadImage(ocean,'assets/fishing/ocean.webp')]).then(([a,b])=>{artReady=a;assetFailed=!a||!b;updateHome();if(view==='book')renderBook();if(view==='gallery')renderGallery();if(assetFailed)toast('部分海洋素材未載入，請重新整理後再開始。');});
const sourceCanvas=new Map();
function fishImage(id){if(sourceCanvas.has(id))return sourceCanvas.get(id);if(!artReady)return null;const i=D.ids.indexOf(id);if(i<0)return null;const [sx,sy,sw,sh]=D.bounds[i],c=document.createElement('canvas');c.width=sw;c.height=sh;c.getContext('2d').drawImage(atlas,sx,sy,sw,sh,0,0,sw,sh);sourceCanvas.set(id,c);return c;}
function sprite(c,id,x,y,w,h,dir=1,alpha=1){const img=fishImage(id);if(!img)return;const scale=Math.min(w/img.width,h/img.height);c.save();c.globalAlpha=alpha;c.translate(x,y);c.scale(dir*(id==='whale'?-1:1),1);c.drawImage(img,-img.width*scale/2,-img.height*scale/2,img.width*scale,img.height*scale);c.restore();}
function thumb(id,w=280,h=160){const c=document.createElement('canvas');c.width=w;c.height=h;sprite(c.getContext('2d'),id,w/2,h/2,w*.88,h*.9);return c;}
let view='home',returnView='home',bookFilter=-1,wallOnly=false,rod='allround',bait='shrimp',draft=null,dirty=false,stroke=null;
let trip=null,W=0,H=0,seaTop=0,seaBottom=0,swimmers=[],lastFrame=0;
function show(id){view=id;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));window.scrollTo(0,0);if(id==='home')updateHome();if(id==='sea')resize();if(id==='book')renderBook();if(id==='gallery')renderGallery();}
function updateHome(){$('book-count').textContent=`${Object.keys(save.records).length} / ${D.fish.length}`;$('art-count').textContent=`${save.works.length} 件`;$('casual-start').disabled=!artReady;$('challenge-select').disabled=!artReady;}
function openPage(id){if(trip?.phase==='fight'||trip?.phase==='cast'){toast('請先完成這一竿。');return;}if(view==='studio'&&dirty&&!confirm('這張魚拓尚未收藏，確定離開工房？'))return;if(view==='home'||view==='sea')returnView=view;show(id);}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPage(b.dataset.open));
document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show(returnView==='sea'&&trip&&!trip.finished?'sea':'home'));
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close();});
function setupOptions(){for(const [list,target,key]of [[D.rods,'rod-options','rod'],[D.baits,'bait-options','bait']]){$(target).replaceChildren();for(const item of list){const b=document.createElement('button');b.className='option'+((key==='rod'?rod:bait)===item.id?' selected':'');b.setAttribute('aria-pressed',String((key==='rod'?rod:bait)===item.id));b.innerHTML=`${esc(item.name)}<small>${esc(item.hint)}</small>`;b.onclick=()=>{if(key==='rod')rod=item.id;else bait=item.id;setupOptions();};$(target).appendChild(b);}}}
$('challenge-select').onclick=()=>{setupOptions();$('setup').showModal();};$('casual-start').onclick=()=>startTrip('casual');$('challenge-start').onclick=()=>{$('setup').close();startTrip('challenge');};
function startTrip(mode){if(!artReady){toast('魚類素材尚未就緒，請稍候或重新整理。');return;}trip={mode,casts:0,score:0,catches:[],zone:0,phase:'idle',elapsed:0,finished:false,held:false};returnView='sea';show('sea');spawnSwimmers();setZone(0);$('mode-label').textContent=mode==='casual'?'休閒':'挑戰';$('tackle-label').textContent=mode==='casual'?'自動收線 · 輕鬆收藏':`${D.rods.find(r=>r.id===rod).name} · ${D.baits.find(b=>b.id===bait).name}`;$('fight').hidden=true;message('選水層，再點水下位置下竿。魚鉤只在選定水層吸引魚群。');updateTrip();}
function message(s){$('sea-message').textContent=s;}
function resize(){if(view!=='sea')return;const c=$('sea-canvas'),r=c.getBoundingClientRect();W=r.width||innerWidth;H=r.height||innerHeight;const d=Math.min(devicePixelRatio||1,2);c.width=Math.round(W*d);c.height=Math.round(H*d);c.getContext('2d').setTransform(d,0,0,d,0,0);seaTop=H*.25;seaBottom=Math.max(seaTop+100,H-165);}
window.addEventListener('resize',resize);
function spawnSwimmers(){swimmers=[];for(let z=0;z<4;z++){const pool=D.fish.filter(f=>f.zone===z);for(let n=0;n<5;n++){const f=pool[n%pool.length];swimmers.push({id:f.id,zone:z,x:Math.random(),y:rand(.15,.85),dir:Math.random()<.5?1:-1,speed:rand(.014,.035),phase:Math.random()*6.28});}}}
function setZone(z){if(!trip||!['idle','settled'].includes(trip.phase))return;trip.zone=z;renderDepths();$('zone-name').textContent=`${D.zones[z].name} · ${D.zones[z].place}`;$('zone-hint').textContent=D.zones[z].hint;}
function renderDepths(){$('depths').replaceChildren();D.zones.forEach((z,i)=>{const b=document.createElement('button');b.textContent=z.name;b.className=i===trip.zone?'selected':'';b.setAttribute('aria-pressed',String(i===trip.zone));b.disabled=!['idle','settled'].includes(trip.phase);b.onclick=()=>setZone(i);$('depths').appendChild(b);});}
function updateTrip(){$('casts').textContent=trip.casts;$('points').textContent=`${trip.score} 分`;$('cast').disabled=trip.phase!=='idle'||trip.casts>=20;$('cast').innerHTML=trip.phase==='idle'?'下竿 <span>→</span>':'釣行中…';renderDepths();}
function pickFish(zone,random=Math.random){const pool=D.fish.filter(f=>f.zone===zone);const weights=pool.map(f=>f.weight*(trip?.mode==='challenge'&&f.bait===bait?2.2:1));let roll=random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<pool.length;i++){roll-=weights[i];if(roll<=0)return pool[i];}return pool[pool.length-1];}
function cast(x=.5,z=trip?.zone){if(!trip||view!=='sea'||trip.phase!=='idle'||trip.casts>=20)return;setZone(z);trip.casts++;trip.phase='cast';trip.elapsed=0;trip.target=pickFish(z);trip.x=clamp(x,.1,.9);trip.size=Math.round(rand(...trip.target.size)*10)/10;trip.phaseTime=rand(2.6,4.3);message(`魚餌正沉入${D.zones[z].name}…等待魚影靠近。`);updateTrip();}
$('cast').onclick=()=>cast();$('sea-canvas').addEventListener('pointerdown',e=>{if(!trip||e.target!==$('sea-canvas'))return;const r=e.target.getBoundingClientRect(),y=e.clientY-r.top;if(y<seaTop||y>seaBottom)return;const z=clamp(Math.floor((y-seaTop)/(seaBottom-seaTop)*4),0,3);cast((e.clientX-r.left)/W,z);});
function beginFight(){trip.phase='fight';trip.elapsed=0;trip.tension=35;trip.progress=0;trip.slack=0;trip.held=false;trip.mood='steady';$('fight-name').textContent=trip.target.name;$('fight').hidden=false;$('reel').classList.remove('held');message('魚上鉤了！按住收線，張力過高就放開。');updateFight();}
function setHeld(value){if(trip?.phase!=='fight')return;trip.held=value;$('reel').classList.toggle('held',value);$('reel').textContent=value?'正在收線 · 放開鬆線':'按住收線';}
$('reel').onpointerdown=e=>{e.preventDefault();$('reel').setPointerCapture(e.pointerId);setHeld(true);};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('reel').addEventListener(name,()=>setHeld(false));$('reel').onkeydown=e=>{if([' ','Enter'].includes(e.key)){e.preventDefault();setHeld(true);}};$('reel').onkeyup=e=>{if([' ','Enter'].includes(e.key))setHeld(false);};$('reel').onblur=()=>setHeld(false);document.addEventListener('visibilitychange',()=>{lastFrame=0;setHeld(false);});window.addEventListener('blur',()=>setHeld(false));
$('release').onclick=()=>{if(trip?.phase==='fight')settle(false,'已放流，這次相遇留在海裡。');};
function updateFight(){$('tension-fill').style.width=clamp(trip.tension,0,100)+'%';$('tension-number').textContent=Math.round(trip.tension)+'%';$('progress-fill').style.width=clamp(trip.progress,0,100)+'%';$('progress-number').textContent=Math.round(trip.progress)+'%';$('fish-mood').textContent=trip.mood==='burst'?'正在衝刺 · 適時鬆線':trip.mood==='rest'?'暫時平靜 · 收線時機':'穩定拉扯';}
function fightStep(dt){const r=D.rods.find(r=>r.id===rod),f=trip.target,cycle=trip.elapsed%6;trip.mood=f.pattern==='steady'?(cycle<4?'steady':'rest'):(cycle<1.8?'burst':cycle<4?'rest':'steady');const pull=trip.mood==='burst'?1.65:trip.mood==='rest'?.55:1;
  if(trip.held){trip.tension+=(9*f.power*pull/r.relief)*dt;trip.progress+=(10*r.gain/(.8+f.power*.25))*(trip.tension>85?.65:1)*dt;trip.slack=0;}else{trip.tension-=16*r.relief*dt;trip.progress-=1.5*dt;if(trip.tension<12)trip.slack+=dt;else trip.slack=0;}
  trip.tension=clamp(trip.tension,0,100);trip.progress=clamp(trip.progress,0,100);updateFight();if(trip.tension>=100)settle(false,'魚線斷了。下次在衝刺前先鬆線。');else if(trip.slack>4)settle(false,'魚鉤鬆脫了。保持一點張力，魚才不會跑掉。');else if(trip.progress>=100)settle(true);else if(trip.elapsed>75)settle(false,'這場拉鋸太久了，魚已游回海中。');}
function settle(success,reason){if(!trip||trip.phase==='settled'||trip.finished)return;trip.held=false;$('fight').hidden=true;trip.phase='settled';trip.elapsed=0;if(success){const f=trip.target,record=save.records[f.id],isNew=!record;const item={fishId:f.id,size:trip.size,date:new Date().toISOString(),mode:trip.mode,rod:trip.mode==='challenge'?rod:'auto',bait:trip.mode==='challenge'?bait:'auto',points:f.points};trip.catches.push(item);trip.score+=f.points;save.records[f.id]={count:(record?.count||0)+1,max:Math.max(record?.max||0,item.size),first:record?.first||item.date,largest:(!record?.largest||item.size>=(record?.max||0))?item:record.largest};persist();message(`${isNew?'新魚種發現！ ':''}${f.name} · ${item.size} cm · +${f.points} 分${isNew?'，已解鎖魚拓':''}`);}else message(reason||'魚群游開了，再換個位置試試。');updateTrip();}
function finishTrip(){if(!trip||trip.finished)return;trip.finished=true;trip.phase='done';const previous=save.best[trip.mode]||0;save.best[trip.mode]=Math.max(previous,trip.score);persist();$('result-score').textContent=trip.score+' 分';$('result-best').textContent=`${trip.mode==='casual'?'休閒':'挑戰'} · ${trip.catches.length} 次釣獲 · ${trip.score>previous?'新紀錄！':'個人最佳 '+save.best[trip.mode]+' 分'}`;const list=$('catch-list');list.replaceChildren();if(!trip.catches.length)list.innerHTML='<p>這趟沒有釣獲，下次試試不同水層。</p>';for(const item of [...trip.catches].reverse()){const f=find(item.fishId),row=document.createElement('div');row.className='catch-row';row.appendChild(thumb(f.id));const text=document.createElement('div');text.innerHTML=`${esc(f.name)}<small>${item.size} cm · ${D.zones[f.zone].name}</small>`;row.appendChild(text);const pts=document.createElement('b');pts.textContent='+'+item.points;row.appendChild(pts);list.appendChild(row);}$('result').showModal();}
$('again').onclick=()=>{$('result').close();startTrip(trip.mode);};$('result-home').onclick=()=>{$('result').close();trip=null;returnView='home';show('home');};$('result-book').onclick=()=>{$('result').close();returnView='home';show('book');};$('result').addEventListener('cancel',()=>{returnView='home';show('home');});
$('leave-sea').onclick=()=>{if(trip?.casts&&!trip.finished&&!confirm('返航會結束本局；已捕獲的圖鑑與魚拓都會保留。確定返航？'))return;if(trip?.casts&&!trip.finished){$('fight').hidden=true;finishTrip();}else{trip=null;show('home');}};
function renderSea(time){const c=$('sea-canvas').getContext('2d'),waterH=seaBottom-seaTop;c.clearRect(0,0,W,H);if(ocean.complete&&ocean.naturalWidth){const iw=ocean.naturalWidth,ih=ocean.naturalHeight,sw=Math.min(iw,W/(H/ih)),sx=(iw-sw)/2;c.drawImage(ocean,sx,0,sw,ih*.145,0,0,W,seaTop);c.drawImage(ocean,sx,ih*.145,sw,ih*.855,0,seaTop,W,H-seaTop);}else{c.fillStyle='#08536e';c.fillRect(0,0,W,H);}c.fillStyle='#00132b26';c.fillRect(0,seaTop,W,H);
  for(let i=0;i<4;i++){const y=seaTop+waterH*i/4;if(i===trip.zone){c.fillStyle='#99e3d911';c.fillRect(0,y,W,waterH/4);c.strokeStyle='#cff9ed50';c.setLineDash([4,8]);c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke();c.setLineDash([]);}c.font='11px system-ui';c.fillStyle=i===trip.zone?'#e8eee0':'#a3c9d199';c.fillText(D.zones[i].name+(i===trip.zone?' · 目前下竿水層':''),16,y+21);}
  for(const s of swimmers){const y=seaTop+waterH*(s.zone+s.y)/4+Math.sin(time+s.phase)*3;const scale=s.id==='oarfish'?110:s.id==='sunfish'?80:60;sprite(c,s.id,s.x*W,y,scale,70,s.dir,s.zone===trip.zone?.95:.5);}
  sprite(c,'boat',W*.5,seaTop-20,130,95);sprite(c,'turtle',W*.87,seaTop+waterH*.2,70,50,-1,.45);sprite(c,'manta',W*.14,seaTop+waterH*.65,85,55,1,.35);
  c.strokeStyle='#dff9ff44';for(let i=0;i<16;i++){const y=seaTop+((i*87-time*11)%Math.max(1,H-seaTop)+(H-seaTop))%(H-seaTop);c.beginPath();c.arc((i*113+Math.sin(time+i)*8)%W,y,1+i%3,0,Math.PI*2);c.stroke();}
  if(['cast','fight'].includes(trip.phase)){const targetY=seaTop+waterH*(trip.zone+.55)/4,progress=trip.phase==='fight'?1:Math.min(1,trip.elapsed/1.4),hx=W*(.5+(trip.x-.5)*progress),hy=seaTop+(targetY-seaTop)*progress;c.strokeStyle='#f4e7b8';c.lineWidth=1.4;c.beginPath();c.moveTo(W*.51,seaTop-35);c.lineTo(hx,hy);c.stroke();c.beginPath();c.arc(hx+4,hy,5,0,Math.PI);c.stroke();if(trip.phase==='fight')sprite(c,trip.target.id,hx+25,hy+10,88,70,Math.sin(time*2)>0?1:-1);else if(trip.elapsed>1.6)sprite(c,trip.target.id,hx+80*(1-clamp((trip.elapsed-1.6)/(trip.phaseTime-1.6),0,1)),hy+7,65,50,-1);}
}
function tick(now){const dt=lastFrame?Math.min(.05,(now-lastFrame)/1000):0;lastFrame=now;if(view==='sea'&&trip&&!document.hidden&&!$('detail').open&&!$('result').open){trip.elapsed+=dt;for(const s of swimmers){s.x+=s.speed*s.dir*dt;if(s.x>1.1)s.x=-.1;if(s.x<-.1)s.x=1.1;}if(trip.phase==='cast'&&trip.elapsed>=trip.phaseTime){if(trip.mode==='challenge')beginFight();else settle(true);}else if(trip.phase==='fight')fightStep(dt);else if(trip.phase==='settled'&&trip.elapsed>1.7){if(trip.casts>=20)finishTrip();else{trip.phase='idle';updateTrip();}}renderSea(now/1000);}requestAnimationFrame(tick);}requestAnimationFrame(tick);
function renderBook(){$('collection-progress').textContent=`${Object.keys(save.records).length} / ${D.fish.length}`;$('legacy-note').textContent=save.legacy.length?`已保留 ${save.legacy.length} 筆舊版發現 ID；與本章對應的條目已解鎖。舊版未記錄尺寸與次數，因此不補造紀錄。`:'尚無舊版發現紀錄。';$('book-filters').replaceChildren();['全部',...D.zones.map(z=>z.name)].forEach((name,i)=>{const b=document.createElement('button');b.textContent=name;b.className=bookFilter===i-1?'selected':'';b.onclick=()=>{bookFilter=i-1;renderBook();};$('book-filters').appendChild(b);});const grid=$('fish-grid');grid.replaceChildren();D.fish.forEach((f,i)=>{if(bookFilter!==-1&&f.zone!==bookFilter)return;const r=save.records[f.id],b=document.createElement('button');b.className='fish-card'+(r?'':' locked');b.setAttribute('aria-label',`${f.name}，${r?'已發現':'未發現'}，查看圖鑑`);b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')}</span>`;b.appendChild(thumb(f.id));const label=document.createElement('div');label.innerHTML=`<h3>${f.name}</h3><small>${D.zones[f.zone].name} · ${f.rarity}</small><span class="found">${r?(r.count?`已捕獲 ${r.count} 次 · 最大 ${r.max} cm`:'舊版發現 · 可製作魚拓'):'尚未相遇 · 查看生態'}</span>`;b.appendChild(label);b.onclick=()=>openFish(f.id);grid.appendChild(b);});}
function dateText(date){return date&&!Number.isNaN(Date.parse(date))?new Date(date).toLocaleDateString('zh-TW'):'未記錄';}
function openFish(id){const f=find(id),r=save.records[id],body=$('detail-body');body.innerHTML=`<p class="eyebrow">OCEAN FIELD NOTES / ${f.rarity}</p><h2>${f.name}</h2><p class="latin">${esc(f.latin)}</p>`;const c=thumb(id,500,240);c.className='fish-detail';body.appendChild(c);const info=document.createElement('div');info.innerHTML=`<div class="stat-grid"><div><small>真實棲息環境</small>${f.habitat}</div><div><small>真實食性</small>${f.diet}</div><div><small>遊戲紀錄 / 最大尺寸</small>${r?.max?r.max+' cm':'尚無尺寸紀錄'}</div><div><small>首次捕獲 / 累計</small>${dateText(r?.first)} · ${r?.count||0} 次</div></div><p>${f.note}</p><p><a href="${f.source}" target="_blank" rel="noopener noreferrer">閱讀生態來源 ↗</a> <small class="muted">查核 ${D.reviewed}</small></p><p class="muted">遊戲提示：${D.zones[f.zone].place}出沒；${D.baits.find(b=>b.id===f.bait).name}增加遇見機會。${f.pattern==='burst'?'衝刺後的平靜期適合收線。':f.pattern==='pulse'?'拉力間歇變化，注意張力。':'拉力持續，分段收線較穩。'}遊戲尺寸與深度不等於生態紀錄。</p>`;body.appendChild(info);const b=document.createElement('button');b.className='primary';b.textContent=r?'開始製作魚拓':'釣獲後解鎖魚拓';b.disabled=!r||!artReady;b.onclick=()=>{$('detail').close();startStudio(id);};body.appendChild(b);$('detail').showModal();}
// Fish prints use the same atlas silhouette and luminance texture as the ocean sprite.
const PW=1000,PH=660,papers={ivory:'#f3eddd',sand:'#dfccaa',mist:'#d9e4df'};
function blankDraft(id){const latest=trip?.catches.slice().reverse().find(c=>c.fishId===id);return {id:crypto.randomUUID(),fishId:id,title:find(id).name+'・海的記憶',signature:'',date:new Date().toISOString(),capture:latest?{...latest}:cleanCapture(save.records[id]?.largest),paper:'ivory',base:'#254c60',seal:true,pinned:false,strokes:[]};}
function startStudio(id){if(!save.records[id]||!artReady)return;draft=blankDraft(id);dirty=false;stroke=null;$('studio-species').textContent=find(id).name;$('art-title').value=draft.title;$('signature').value='';$('paper-type').value=draft.paper;$('seal').checked=true;$('ink-color').value=draft.base;show('studio');renderPalette();renderPrint($('print-canvas'),draft);}
const maskCache=new Map();
function fishMask(id){if(maskCache.has(id))return maskCache.get(id);const image=fishImage(id);if(!image)return null;const c=document.createElement('canvas');c.width=PW;c.height=PH;const ctx=c.getContext('2d'),scale=Math.min(760/image.width,330/image.height),w=image.width*scale,h=image.height*scale;ctx.drawImage(image,500-w/2,310-h/2,w,h);const pixels=ctx.getImageData(0,0,PW,PH),d=pixels.data;for(let i=0;i<d.length;i+=4){const l=(d[i]*.299+d[i+1]*.587+d[i+2]*.114)/255;const speck=((i/4*17+Math.floor(i/4/PW)*31)%97)/97;d[i]=d[i+1]=d[i+2]=0;d[i+3]=Math.round(d[i+3]*(.23+(1-l)*.7)*(speck<.11?.45:1));}ctx.putImageData(pixels,0,0);maskCache.set(id,c);return c;}
function renderPrint(canvas,w){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.save();c.scale(canvas.width/PW,canvas.height/PH);c.fillStyle=papers[w.paper];c.fillRect(0,0,PW,PH);for(let i=0;i<1500;i++){const x=(i*173.123)%PW,y=(i*93.517)%PH;c.fillStyle=i%2?'#ffffff25':'#7263400a';c.fillRect(x,y,1+i%4,.7);}c.strokeStyle='#8c856322';c.strokeRect(29,29,PW-58,PH-58);
  const layer=document.createElement('canvas');layer.width=PW;layer.height=PH;const ink=layer.getContext('2d');ink.fillStyle=w.base;ink.fillRect(0,0,PW,PH);for(const s of w.strokes){if(!s.points.length)continue;ink.save();ink.strokeStyle=s.color;ink.fillStyle=s.color;ink.globalAlpha=s.opacity;ink.lineWidth=s.size;ink.lineCap='round';ink.lineJoin='round';if(s.points.length===1){ink.beginPath();ink.arc(...s.points[0],s.size/2,0,Math.PI*2);ink.fill();}else{ink.beginPath();s.points.forEach(([x,y],i)=>i?ink.lineTo(x,y):ink.moveTo(x,y));ink.stroke();}ink.restore();}ink.globalCompositeOperation='destination-in';const mask=fishMask(w.fishId);if(mask)ink.drawImage(mask,0,0);else ink.clearRect(0,0,PW,PH);c.drawImage(layer,0,0);
  const f=find(w.fishId);c.fillStyle='#34514f';c.font='26px Story Serif,serif';c.fillText(w.title||f.name,65,88,860);c.font='13px Georgia,serif';c.fillStyle='#718178';c.fillText('GYOTAKU / 海 洋 手 記',66,114);c.font='20px Story Serif,serif';c.fillStyle='#435b52';c.fillText(f.name,65,554);c.font='13px Georgia,serif';c.fillText(w.capture?`${w.capture.size} cm · ${dateText(w.capture.date)} · 遊戲捕獲紀錄`:'舊版發現 · 尺寸未記錄',65,582);c.textAlign='right';c.font='23px Story Serif,serif';c.fillText(w.signature||'海的旅人',w.seal?845:925,559,260);c.font='12px Georgia,serif';c.fillStyle='#8c9380';c.fillText(dateText(w.date),w.seal?845:925,584);if(w.seal){c.strokeStyle='#a34337';c.lineWidth=3;c.strokeRect(876,535,49,49);c.fillStyle='#a34337';c.textAlign='center';c.font='17px Story Serif,serif';c.fillText('海',900,555);c.fillText('藏',900,575);}c.restore();}
function renderPalette(){$('palette').replaceChildren();for(const color of ['#253d42','#254c60','#476b66','#a34736','#98693c','#73648b']){const b=document.createElement('button');b.style.background=color;b.className=color===$('ink-color').value?'selected':'';b.setAttribute('aria-label','選擇墨色 '+color);b.onclick=()=>{$('ink-color').value=color;renderPalette();};$('palette').appendChild(b);}}
$('ink-color').oninput=renderPalette;
function syncDraft(){if(!draft)return;draft.paper=$('paper-type').value;draft.title=$('art-title').value.slice(0,36);draft.signature=$('signature').value.slice(0,18);draft.seal=$('seal').checked;dirty=true;renderPrint($('print-canvas'),draft);}
for(const id of ['paper-type','art-title','signature','seal'])$(id).addEventListener('input',syncDraft);
$('fill-ink').onclick=()=>{if(!draft)return;draft.base=$('ink-color').value;dirty=true;renderPrint($('print-canvas'),draft);};$('undo-ink').onclick=()=>{if(!draft)return;draft.strokes.pop();dirty=true;renderPrint($('print-canvas'),draft);};
function brushPoint(e){const r=$('print-canvas').getBoundingClientRect();return [clamp((e.clientX-r.left)/r.width*PW,0,PW),clamp((e.clientY-r.top)/r.height*PH,0,PH)];}
$('print-canvas').onpointerdown=e=>{if(!draft||draft.strokes.length>=160){toast('已達 160 筆筆觸，可先收藏這張作品再製作新作。');return;}e.preventDefault();e.target.setPointerCapture(e.pointerId);stroke={color:$('ink-color').value,size:Number($('brush-size').value),opacity:Number($('ink-opacity').value)/100,points:[brushPoint(e)]};draft.strokes.push(stroke);dirty=true;renderPrint($('print-canvas'),draft);};let brushRAF=false;
$('print-canvas').onpointermove=e=>{if(!stroke||stroke.points.length>=2500)return;const p=brushPoint(e),last=stroke.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])<3)return;stroke.points.push(p);if(!brushRAF){brushRAF=true;requestAnimationFrame(()=>{brushRAF=false;if(draft)renderPrint($('print-canvas'),draft);});}};for(const event of ['pointerup','pointercancel','lostpointercapture'])$('print-canvas').addEventListener(event,()=>{stroke=null;});
$('leave-studio').onclick=()=>{if(dirty&&!confirm('這張魚拓尚未收藏，確定返回圖鑑？'))return;draft=null;dirty=false;show('book');};
$('save-art').onclick=()=>{if(!draft)return;if(save.works.length>=500){toast('收藏已達 500 件，請備份後整理作品。');return;}syncDraft();const artwork=JSON.parse(JSON.stringify(draft));save.works.unshift(artwork);const ok=persist();dirty=false;draft=null;$('save-art').disabled=true;$('peel').hidden=false;setTimeout(()=>{$('peel').hidden=true;$('save-art').disabled=false;wallOnly=false;show('gallery');toast(ok?'魚拓已收入收藏館。':'作品暫存於本次開啟，請立即匯出備份。');},1150);};
$('all-art').onclick=()=>{wallOnly=false;renderGallery();};$('wall-art').onclick=()=>{wallOnly=true;renderGallery();};$('art-filter').onchange=renderGallery;
function renderGallery(){const filter=$('art-filter').value||'all';$('art-filter').innerHTML='<option value="all">所有魚種</option>'+D.fish.map(f=>`<option value="${f.id}">${f.name}</option>`).join('');$('art-filter').value=filter;$('all-art').classList.toggle('selected',!wallOnly);$('wall-art').classList.toggle('selected',wallOnly);const grid=$('art-grid');grid.className='art-grid'+(wallOnly?' wall':'');grid.replaceChildren();const works=save.works.filter(w=>(!wallOnly||w.pinned)&&(filter==='all'||w.fishId===filter));if(!works.length){grid.innerHTML=`<div class="empty"><p class="eyebrow">A PLACE FOR YOUR MEMORIES</p><h3>${wallOnly?'牆上，還有一個位置留給海。':'第一張魚拓，等著你來收藏。'}</h3><p>${wallOnly?'打開收藏冊裡的作品，選擇「掛上展示牆」。':'先釣到一條魚，再從圖鑑進入魚拓工房。'}</p><button id="empty-go">${wallOnly?'回到收藏冊':'去海洋圖鑑'}</button></div>`;$('empty-go').onclick=()=>{if(wallOnly){wallOnly=false;renderGallery();}else show('book');};}for(const w of works){const card=document.createElement('button');card.className='art-card';const canvas=document.createElement('canvas');canvas.width=500;canvas.height=330;renderPrint(canvas,w);card.appendChild(canvas);const cap=document.createElement('div');cap.className='art-caption';cap.textContent=w.title;const sub=document.createElement('small');sub.textContent=`${find(w.fishId).name} · ${dateText(w.date)}${w.pinned?' · 展示中':''}`;cap.appendChild(sub);card.appendChild(cap);card.onclick=()=>openArtwork(w.id);grid.appendChild(card);}updateHome();}
function openArtwork(id){const w=save.works.find(w=>w.id===id);if(!w)return;const body=$('detail-body');body.innerHTML=`<p class="eyebrow">PRIVATE COLLECTION</p><h2>${esc(w.title)}</h2>`;const c=document.createElement('canvas');c.width=1000;c.height=660;c.className='detail-art';renderPrint(c,w);body.appendChild(c);const desc=document.createElement('p');desc.className='muted';desc.textContent=`${find(w.fishId).name} · ${dateText(w.date)} · ${w.signature||'海的旅人'}`;body.appendChild(desc);const row=document.createElement('div');row.className='tool-row';const pin=document.createElement('button');pin.textContent=w.pinned?'從展示牆取下':'掛上展示牆';pin.onclick=()=>{w.pinned=!w.pinned;persist();$('detail').close();renderGallery();};const download=document.createElement('button');download.textContent='匯出 PNG 圖片';download.onclick=()=>c.toBlob(blob=>{if(blob)downloadFile(blob,`魚拓-${find(w.fishId).name}-${w.id.slice(0,8)}.png`);});row.append(pin,download);body.appendChild(row);const remove=document.createElement('button');remove.className='quiet';remove.textContent='刪除此作品';remove.onclick=()=>{if(!confirm('確定刪除這一張魚拓？其他作品與圖鑑紀錄會保留。'))return;save.works=save.works.filter(x=>x.id!==id);persist();$('detail').close();renderGallery();};body.appendChild(remove);$('detail').showModal();}
function downloadFile(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('backup').onclick=()=>downloadFile(new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),'釣魚物語-收藏備份-'+new Date().toISOString().slice(0,10)+'.json');
$('restore').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>12000000)throw Error('備份檔超過 12 MB');const imported=validateSave(JSON.parse(await file.text()));if(!confirm(`匯入 ${imported.works.length} 件作品與 ${Object.keys(imported.records).length} 個圖鑑條目？將與現有收藏合併。`))return;const merged=JSON.parse(JSON.stringify(save)),existing=new Set(merged.works.map(w=>w.id));for(const w of imported.works)if(!existing.has(w.id)){merged.works.push(w);existing.add(w.id);}if(merged.works.length>500)throw Error('合併後超過 500 件作品');for(const [id,r]of Object.entries(imported.records)){const old=merged.records[id];merged.records[id]={count:Math.max(old?.count||0,r.count),max:Math.max(old?.max||0,r.max),first:[old?.first,r.first].filter(Boolean).sort()[0]||null,legacy:!!(old?.legacy||r.legacy),largest:(r.max>=(old?.max||0)?r.largest:old?.largest)||null};}for(const k of ['casual','challenge'])merged.best[k]=Math.max(merged.best[k],imported.best[k]);merged.legacy=[...new Set([...merged.legacy,...imported.legacy])];save=merged;const ok=persist();renderGallery();toast(ok?'備份已合併，既有作品保留。':'已合併但無法永久儲存，請立即匯出備份。');}catch(err){toast('無法匯入：'+err.message);}finally{e.target.value='';}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
updateHome();if(!storageOK)toast('無法讀取本機存檔；請保留原有資料並使用收藏備份。');
// Narrow diagnostics for automated regression; opt-in only on local test page.
if(['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).has('test'))window.FishingTest={get state(){return {save,trip,view,draft,artReady,storageOK};},startTrip,cast,settle,finishTrip,pickFish,fightStep,beginFight,setHeld,show,startStudio,renderPrint,validateSave,persist,setZone,openFish,openArtwork,tick};
})();
